Install-ActionsCache.ps1
Install-Ruby.ps1
Install-PyPy.ps1
Install-Toolset.ps1
Configure-Toolset.ps1
Install-NodeJS.ps1
Install-AndroidSDK.ps1
Install-PowershellAzModules.ps1
Install-Pipx.ps1
Install-Git.ps1
Install-GitHub-CLI.ps1
Install-PHP.ps1
Install-Rust.ps1
Install-Sbt.ps1
Install-Chrome.ps1
Install-EdgeDriver.ps1
Install-Firefox.ps1
Install-Selenium.ps1
Install-IEWebDriver.ps1
Install-Apache.ps1
Install-Nginx.ps1
Install-Msys2.ps1
Install-WinAppDriver.ps1
Install-R.ps1
Install-AWSTools.ps1
Install-DACFx.ps1
Install-MysqlCli.ps1
Install-SQLPowerShellTools.ps1
Install-SQLOLEDBDriver.ps1
Install-DotnetSDK.ps1
Install-Mingw64.ps1
Install-Haskell.ps1
Install-Stack.ps1
Install-Miniconda.ps1
Install-AzureCosmosDbEmulator.ps1
Install-Mercurial.ps1
Install-Zstd.ps1
Install-NSIS.ps1
Configure-Diagnostics.ps1
